#############################################################################
# Makefile for building: ElitraIDE
# Generated by qmake (3.1) (Qt 6.11.1)
# Project:  ElitraIDE.pro
# Template: app
# Command: /usr/sbin/qmake6 -o Makefile ElitraIDE.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -mno-direct-extern-access -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -mno-direct-extern-access -D_REENTRANT $(DEFINES)
INCPATH       = -I. -Isrc -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I. -I/usr/lib/qt6/mkspecs/linux-g++
QMAKE         = /usr/sbin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/sbin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/sbin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ElitraIDE1.0.0
DISTDIR = /home/ratimir/Проекты/Elitra\ IDE/.tmp/ElitraIDE1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib -Wl,-rpath-link,/usr/lib
LIBS          = $(SUBLIBS) /usr/lib/libQt6Widgets.so /usr/lib/libQt6Gui.so /usr/lib/libGLX.so /usr/lib/libOpenGL.so /usr/lib/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/elitrahighlighter.cpp \
		src/languagehighlighter.cpp \
		src/codeeditor.cpp \
		src/outputpanel.cpp \
		src/findreplacepanel.cpp \
		src/findinfilespanel.cpp \
		src/lspclient.cpp \
		src/settingsdialog.cpp \
		src/fileiconprovider.cpp \
		src/activitybar.cpp \
		src/sidebar.cpp \
		src/statusbarmanager.cpp moc_mainwindow.cpp \
		moc_elitrahighlighter.cpp \
		moc_languagehighlighter.cpp \
		moc_codeeditor.cpp \
		moc_outputpanel.cpp \
		moc_findreplacepanel.cpp \
		moc_findinfilespanel.cpp \
		moc_lspclient.cpp \
		moc_settingsdialog.cpp \
		moc_activitybar.cpp \
		moc_sidebar.cpp \
		moc_statusbarmanager.cpp
OBJECTS       = main.o \
		mainwindow.o \
		elitrahighlighter.o \
		languagehighlighter.o \
		codeeditor.o \
		outputpanel.o \
		findreplacepanel.o \
		findinfilespanel.o \
		lspclient.o \
		settingsdialog.o \
		fileiconprovider.o \
		activitybar.o \
		sidebar.o \
		statusbarmanager.o \
		moc_mainwindow.o \
		moc_elitrahighlighter.o \
		moc_languagehighlighter.o \
		moc_codeeditor.o \
		moc_outputpanel.o \
		moc_findreplacepanel.o \
		moc_findinfilespanel.o \
		moc_lspclient.o \
		moc_settingsdialog.o \
		moc_activitybar.o \
		moc_sidebar.o \
		moc_statusbarmanager.o
DIST          = /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/permissions.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/uic.prf \
		/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		ElitraIDE.pro src/mainwindow.h \
		src/elitrahighlighter.h \
		src/languagehighlighter.h \
		src/codeeditor.h \
		src/outputpanel.h \
		src/findreplacepanel.h \
		src/findinfilespanel.h \
		src/lspclient.h \
		src/settingsdialog.h \
		src/fileiconprovider.h \
		src/activitybar.h \
		src/sidebar.h \
		src/statusbarmanager.h \
		src/colors.h src/main.cpp \
		src/mainwindow.cpp \
		src/elitrahighlighter.cpp \
		src/languagehighlighter.cpp \
		src/codeeditor.cpp \
		src/outputpanel.cpp \
		src/findreplacepanel.cpp \
		src/findinfilespanel.cpp \
		src/lspclient.cpp \
		src/settingsdialog.cpp \
		src/fileiconprovider.cpp \
		src/activitybar.cpp \
		src/sidebar.cpp \
		src/statusbarmanager.cpp
QMAKE_TARGET  = ElitraIDE
DESTDIR       = 
TARGET        = ElitraIDE


first: all
####### Build rules

ElitraIDE:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ElitraIDE.pro /usr/lib/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/permissions.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/uic.prf \
		/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		ElitraIDE.pro \
		/usr/lib/libQt6Widgets.prl \
		/usr/lib/libQt6Gui.prl \
		/usr/lib/libQt6Core.prl
	$(QMAKE) -o Makefile ElitraIDE.pro
/usr/lib/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/qt6/mkspecs/common/unix.conf:
/usr/lib/qt6/mkspecs/common/linux.conf:
/usr/lib/qt6/mkspecs/common/sanitize.conf:
/usr/lib/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt6/mkspecs/common/g++-base.conf:
/usr/lib/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/qt6/mkspecs/qconfig.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testinternals_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/qt6/mkspecs/features/qt_config.prf:
/usr/lib/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt6/mkspecs/features/toolchain.prf:
/usr/lib/qt6/mkspecs/features/default_pre.prf:
/usr/lib/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/qt6/mkspecs/features/default_post.prf:
/usr/lib/qt6/mkspecs/features/warn_on.prf:
/usr/lib/qt6/mkspecs/features/permissions.prf:
/usr/lib/qt6/mkspecs/features/qt.prf:
/usr/lib/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/qt6/mkspecs/features/resources.prf:
/usr/lib/qt6/mkspecs/features/moc.prf:
/usr/lib/qt6/mkspecs/features/link_ltcg.prf:
/usr/lib/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/qt6/mkspecs/features/uic.prf:
/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf:
/usr/lib/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/qt6/mkspecs/features/file_copies.prf:
/usr/lib/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/qt6/mkspecs/features/exceptions.prf:
/usr/lib/qt6/mkspecs/features/yacc.prf:
/usr/lib/qt6/mkspecs/features/lex.prf:
ElitraIDE.pro:
/usr/lib/libQt6Widgets.prl:
/usr/lib/libQt6Gui.prl:
/usr/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ElitraIDE.pro

qmake_all: FORCE


all: Makefile ElitraIDE

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/mainwindow.h src/elitrahighlighter.h src/languagehighlighter.h src/codeeditor.h src/outputpanel.h src/findreplacepanel.h src/findinfilespanel.h src/lspclient.h src/settingsdialog.h src/fileiconprovider.h src/activitybar.h src/sidebar.h src/statusbarmanager.h src/colors.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/elitrahighlighter.cpp src/languagehighlighter.cpp src/codeeditor.cpp src/outputpanel.cpp src/findreplacepanel.cpp src/findinfilespanel.cpp src/lspclient.cpp src/settingsdialog.cpp src/fileiconprovider.cpp src/activitybar.cpp src/sidebar.cpp src/statusbarmanager.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_elitrahighlighter.cpp moc_languagehighlighter.cpp moc_codeeditor.cpp moc_outputpanel.cpp moc_findreplacepanel.cpp moc_findinfilespanel.cpp moc_lspclient.cpp moc_settingsdialog.cpp moc_activitybar.cpp moc_sidebar.cpp moc_statusbarmanager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_elitrahighlighter.cpp moc_languagehighlighter.cpp moc_codeeditor.cpp moc_outputpanel.cpp moc_findreplacepanel.cpp moc_findinfilespanel.cpp moc_lspclient.cpp moc_settingsdialog.cpp moc_activitybar.cpp moc_sidebar.cpp moc_statusbarmanager.cpp
moc_mainwindow.cpp: src/mainwindow.h \
		src/activitybar.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include '/home/ratimir/Проекты/Elitra IDE/moc_predefs.h' -I/usr/lib/qt6/mkspecs/linux-g++ -I'/home/ratimir/Проекты/Elitra IDE' -I'/home/ratimir/Проекты/Elitra IDE/src' -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/mainwindow.h -o moc_mainwindow.cpp

moc_elitrahighlighter.cpp: src/elitrahighlighter.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include '/home/ratimir/Проекты/Elitra IDE/moc_predefs.h' -I/usr/lib/qt6/mkspecs/linux-g++ -I'/home/ratimir/Проекты/Elitra IDE' -I'/home/ratimir/Проекты/Elitra IDE/src' -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/elitrahighlighter.h -o moc_elitrahighlighter.cpp

moc_languagehighlighter.cpp: src/languagehighlighter.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include '/home/ratimir/Проекты/Elitra IDE/moc_predefs.h' -I/usr/lib/qt6/mkspecs/linux-g++ -I'/home/ratimir/Проекты/Elitra IDE' -I'/home/ratimir/Проекты/Elitra IDE/src' -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/languagehighlighter.h -o moc_languagehighlighter.cpp

moc_codeeditor.cpp: src/codeeditor.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include '/home/ratimir/Проекты/Elitra IDE/moc_predefs.h' -I/usr/lib/qt6/mkspecs/linux-g++ -I'/home/ratimir/Проекты/Elitra IDE' -I'/home/ratimir/Проекты/Elitra IDE/src' -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/codeeditor.h -o moc_codeeditor.cpp

moc_outputpanel.cpp: src/outputpanel.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include '/home/ratimir/Проекты/Elitra IDE/moc_predefs.h' -I/usr/lib/qt6/mkspecs/linux-g++ -I'/home/ratimir/Проекты/Elitra IDE' -I'/home/ratimir/Проекты/Elitra IDE/src' -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/outputpanel.h -o moc_outputpanel.cpp

moc_findreplacepanel.cpp: src/findreplacepanel.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include '/home/ratimir/Проекты/Elitra IDE/moc_predefs.h' -I/usr/lib/qt6/mkspecs/linux-g++ -I'/home/ratimir/Проекты/Elitra IDE' -I'/home/ratimir/Проекты/Elitra IDE/src' -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/findreplacepanel.h -o moc_findreplacepanel.cpp

moc_findinfilespanel.cpp: src/findinfilespanel.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include '/home/ratimir/Проекты/Elitra IDE/moc_predefs.h' -I/usr/lib/qt6/mkspecs/linux-g++ -I'/home/ratimir/Проекты/Elitra IDE' -I'/home/ratimir/Проекты/Elitra IDE/src' -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/findinfilespanel.h -o moc_findinfilespanel.cpp

moc_lspclient.cpp: src/lspclient.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include '/home/ratimir/Проекты/Elitra IDE/moc_predefs.h' -I/usr/lib/qt6/mkspecs/linux-g++ -I'/home/ratimir/Проекты/Elitra IDE' -I'/home/ratimir/Проекты/Elitra IDE/src' -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/lspclient.h -o moc_lspclient.cpp

moc_settingsdialog.cpp: src/settingsdialog.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include '/home/ratimir/Проекты/Elitra IDE/moc_predefs.h' -I/usr/lib/qt6/mkspecs/linux-g++ -I'/home/ratimir/Проекты/Elitra IDE' -I'/home/ratimir/Проекты/Elitra IDE/src' -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/settingsdialog.h -o moc_settingsdialog.cpp

moc_activitybar.cpp: src/activitybar.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include '/home/ratimir/Проекты/Elitra IDE/moc_predefs.h' -I/usr/lib/qt6/mkspecs/linux-g++ -I'/home/ratimir/Проекты/Elitra IDE' -I'/home/ratimir/Проекты/Elitra IDE/src' -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/activitybar.h -o moc_activitybar.cpp

moc_sidebar.cpp: src/sidebar.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include '/home/ratimir/Проекты/Elitra IDE/moc_predefs.h' -I/usr/lib/qt6/mkspecs/linux-g++ -I'/home/ratimir/Проекты/Elitra IDE' -I'/home/ratimir/Проекты/Elitra IDE/src' -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/sidebar.h -o moc_sidebar.cpp

moc_statusbarmanager.cpp: src/statusbarmanager.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include '/home/ratimir/Проекты/Elitra IDE/moc_predefs.h' -I/usr/lib/qt6/mkspecs/linux-g++ -I'/home/ratimir/Проекты/Elitra IDE' -I'/home/ratimir/Проекты/Elitra IDE/src' -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/statusbarmanager.h -o moc_statusbarmanager.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src/mainwindow.h \
		src/activitybar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/activitybar.h \
		src/codeeditor.h \
		src/outputpanel.h \
		src/elitrahighlighter.h \
		src/languagehighlighter.h \
		src/findreplacepanel.h \
		src/findinfilespanel.h \
		src/lspclient.h \
		src/settingsdialog.h \
		src/sidebar.h \
		src/statusbarmanager.h \
		src/fileiconprovider.h \
		src/colors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

elitrahighlighter.o: src/elitrahighlighter.cpp src/elitrahighlighter.h \
		src/colors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o elitrahighlighter.o src/elitrahighlighter.cpp

languagehighlighter.o: src/languagehighlighter.cpp src/languagehighlighter.h \
		src/colors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o languagehighlighter.o src/languagehighlighter.cpp

codeeditor.o: src/codeeditor.cpp src/codeeditor.h \
		src/colors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o codeeditor.o src/codeeditor.cpp

outputpanel.o: src/outputpanel.cpp src/outputpanel.h \
		src/colors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o outputpanel.o src/outputpanel.cpp

findreplacepanel.o: src/findreplacepanel.cpp src/findreplacepanel.h \
		src/codeeditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o findreplacepanel.o src/findreplacepanel.cpp

findinfilespanel.o: src/findinfilespanel.cpp src/findinfilespanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o findinfilespanel.o src/findinfilespanel.cpp

lspclient.o: src/lspclient.cpp src/lspclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lspclient.o src/lspclient.cpp

settingsdialog.o: src/settingsdialog.cpp src/settingsdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingsdialog.o src/settingsdialog.cpp

fileiconprovider.o: src/fileiconprovider.cpp src/fileiconprovider.h \
		src/colors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fileiconprovider.o src/fileiconprovider.cpp

activitybar.o: src/activitybar.cpp src/activitybar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o activitybar.o src/activitybar.cpp

sidebar.o: src/sidebar.cpp src/sidebar.h \
		src/fileiconprovider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sidebar.o src/sidebar.cpp

statusbarmanager.o: src/statusbarmanager.cpp src/statusbarmanager.h \
		src/fileiconprovider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statusbarmanager.o src/statusbarmanager.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_elitrahighlighter.o: moc_elitrahighlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_elitrahighlighter.o moc_elitrahighlighter.cpp

moc_languagehighlighter.o: moc_languagehighlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_languagehighlighter.o moc_languagehighlighter.cpp

moc_codeeditor.o: moc_codeeditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_codeeditor.o moc_codeeditor.cpp

moc_outputpanel.o: moc_outputpanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_outputpanel.o moc_outputpanel.cpp

moc_findreplacepanel.o: moc_findreplacepanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_findreplacepanel.o moc_findreplacepanel.cpp

moc_findinfilespanel.o: moc_findinfilespanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_findinfilespanel.o moc_findinfilespanel.cpp

moc_lspclient.o: moc_lspclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lspclient.o moc_lspclient.cpp

moc_settingsdialog.o: moc_settingsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingsdialog.o moc_settingsdialog.cpp

moc_activitybar.o: moc_activitybar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_activitybar.o moc_activitybar.cpp

moc_sidebar.o: moc_sidebar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sidebar.o moc_sidebar.cpp

moc_statusbarmanager.o: moc_statusbarmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_statusbarmanager.o moc_statusbarmanager.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

